CREATE TABLE servicos (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    slug VARCHAR(180) NOT NULL UNIQUE,
    valor FLOAT NOT NULL,
    descricao TEXT,
    resumo VARCHAR(255),
    caminho_imagens TEXT,
    quantidade_imagens INT UNSIGNED NOT NULL DEFAULT 0,
    prioridade INT NOT NULL DEFAULT 0,
    status_venda BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);